### ISSUE TITLE
Populating x5u/x5c fields

### ISSUE THREAD

**Issue by lumjjb** [latchset/jwcrypto#146]
Is there currently a way to populate `x5u/x5c` fields? 

Would there be interest if we could provide a PR for the feature if not currently possible?

**Comment by simo5** [comment]
JWK, JWS and JWE classes do know about the existence of these parameters, but they do not know how to handle them, so if they are marked critical the implementation will raise an error.
However if they are not critical they will be retained as is.

Implementing support for directly downloading certificates (x5u) or validating the certificate chain (x5c) would not be simple as I do not want to force dependencies on additional python modules and also I do not want to perform network operations behind the back of the main application.

However there is a todo in the code about support custom headers so that an application can make use of them. What we'd need is probably a way to register new entries in JWSHeaderRegistry via some setter/class function and also have a way to provide a list of validation functions/objects for custom handling.

Once we have that than we can also have a module that implements basic URL and Chain validation handling that applications can use or override as they need.

I can help steering the design if you want to try to come up with a proposal.

**Comment by lumjjb** [comment]
>However there is a todo in the code about support custom headers so that an application can make use of them. What we'd need is probably a way to register new entries in JWSHeaderRegistry via some setter/class function and also have a way to provide a list of validation functions/objects for custom handling.

Thanks @simo5, that sounds perfect! Understand the concern of dependencies in this respect. This in itself would be suitable for our purposes, we have an external component that does the validation, so all we need is a way to add the entry to `JWSHeaderRegistry`.

>I can help steering the design if you want to try to come up with a proposal.

We are finishing up some other existing work, but this would be the next thing we need to look at, so we will share with you what we have in mind for that. :)

**Comment by simo5** [comment]
ack

**Comment by lumjjb** [comment]
I was looking through the library, and it seems like the safest way to add headers would be to use the existing `_merge_check_headers` function. I noticed that registry check was not in the function itself, so added it as a wrapper:

For `jwcrypto/jws.py`:
```
    def add_headers (self, *headers):
        for hn in headers:
            if hn is None:
                continue
            for h in list(hn.keys()):
                if h not in JWSHeaderRegistry:
                    raise InvalidJWSObject('Header not valid: "%s"' % h)

        self.objects['protected'] = json_encode(self._merge_check_headers (json_decode(self.objects['protected']), *headers))
```

I am thinking to instead move the check for `if h not in JWSHeaderRegistry:` into `_merge_check_headers`. 

For the getter/setters, are you thinking that we would have one for headers, or one for every possible header field?

```
; token.header = {'x5c' : 'some-val'} 
; token.header == {'x5c' : 'some-val', ...other existing header fields} 

# Or

token.header.x5c = 'some-val'
```

**Comment by simo5** [comment]
What we need is a way to extend the Registry with custom parameter names, and application provided checkers.
Then all internal functions will work just fine without needing any changes.

Something like:
token.header_registry.add(name, checker_fn)

Then add a function:
def check_header(name, value):
    if name not self.header_registry:
         return self.header_registry[name].check_fn(value)
    if name in JWSHeaderRegistry:
         return ...
    raise InvalidJWSObject('Header not valid: "%s"' % h)
      
Bonus points if this code can be shared with JWE so we reuse.

**Comment by lumjjb** [comment]
Gotcha, let me try to put something together.

**Comment by lumjjb** [comment]
We managed to figure out to get what we needed to do without any changes, but i think this is a good feature to have in the library, so went ahead to take a stab at it. :)

Let me know of any feedback you have on this, and if I have misunderstood the scope.

**Comment by lumjjb** [comment]
@simo5 shall we close this issue as resolved?  :)

**Comment by simo5** [comment]
We shall!
