### ISSUE TITLE
[SECURITY] Algorithm Confusion Through kid Header

### ISSUE THREAD

**Issue by paragonie-security** [latchset/jwcrypto#235]
First, let us note that the `alg` header is correctly being validated.

https://github.com/latchset/jwcrypto/blob/ea36353202bb6f0dab3340f38e6273a5681cc382/jwcrypto/jwt.py#L483-L485

However, if a `kid` header is being used by an application, jwcrypto will pass a key to the cryptographic verification routine without first asserting that the key's intended algorithm matches the token header's.

https://github.com/latchset/jwcrypto/blob/ea36353202bb6f0dab3340f38e6273a5681cc382/jwcrypto/jwt.py#L495-L519

https://github.com/latchset/jwcrypto/blob/ea36353202bb6f0dab3340f38e6273a5681cc382/jwcrypto/jwk.py#L1192-L1199

This is congruent to the problem in https://github.com/firebase/php-jwt/issues/351 https://seclists.org/fulldisclosure/2021/Aug/14

Note: This particular sharp edge isn't covered by the [JWT Best Practices RFC](https://datatracker.ietf.org/doc/html/rfc8725).

**Comment by simo5** [comment]
So first of all, this project has a clear security policy you DID NOT follow: https://github.com/latchset/jwcrypto/security/policy

Secondly, if you look at the code you are pointing at you will see that in absence of a kid we try *all* keys.

This is because we defer validation of key type to the algorithm handling which uses typed keys to handle cryptographic operations, via the get_op_key function: https://github.com/latchset/jwcrypto/blob/ea36353202bb6f0dab3340f38e6273a5681cc382/jwcrypto/jwk.py#L802

This function returns a python cryptography object for all cases except the 'oct' type. In the 'oct' case a base64 encoded string is returned, and all calling functions try to either decode it, or use a key object. If pyca object is passed to base64_decode then the code will retuen an exception. if a byte64 encoded string is used in a EC or RSA operation then when the object is dereferenced to use a sign() or verify() method it will also throw an exception. And if a RSA key is used with an EC operation (or vice versa) then pyca will assert.

We could probably pass the expected key type to the get_op_key() function, but that would just return a nicer error message, it is not required for security.

Please do better or I will automatically close reports from you in the future, I am not here to waste time on poor research.

If you think I missed something, please provide a reproducer, this is python and json objects, it is very simply to provide me with a token, keys and 3 lines of code to test out anything (See the examples in the documentation).
