### ISSUE TITLE
Indirect cryptography dep is unpinned

### ISSUE THREAD

**Issue by Jecoms** [latchset/jwcrypto#298]
Ran into an issue for a build when the latest `cryptography` major version 38 was pulled in as an indirect dependency for this library.

`setup.py` is only requiring `>= 2.3`

The build issue was resolved once pinning `cryptography` to the last major version 37.

**Comment by Jecoms** [comment]
It's related to building for an aws lambda environment.

This is the issue raised on the cryptography side (with their suggested resolution):
https://github.com/pyca/cryptography/issues/6391#issuecomment-1110124861

**Comment by simo5** [comment]
To be honest I do not see how this is a jwcrypto problem.

We intentionally do not artificially restrict which cryptography version we require, because we want users to be able to always use the very latest cryptography with all related security fixes.

I think that if a jwcrypto user has a problem with a specific cryptography version they should do the pinning in their project instead.

**Comment by Jecoms** [comment]
That's fair. At least this will be an artifact for anyone using this lib and having errors from cryptography pulled in only as an indirect dep.
