### ISSUE TITLE
JWE API feedback

### ISSUE THREAD

**Issue by hannosch** [latchset/jwcrypto#53]
First of all thanks for an excellent library. I'm using the library for JWE de/encryption in combination with square/js-jose.

It took me a while to figure out the API and what I ended up with is:
```
def encrypt(plaintext, public_jwk)
    protected = '{"alg":"RSA-OAEP","enc":"A256GCM"}'
    jwe = JWE(plaintext=plaintext, protected=protected)
    jwe.add_recipient(public_jwk)
    ciphertext = jwe.serialize(compact=True)
    return ciphertext

def decrypt(ciphertext, private_jwk):
    jwe = JWE()
    jwe.deserialize(ciphertext, key=private_jwk)
    plaintext = jwe.payload.decode('utf-8')
    return plaintext
```
Unfortunately those two functions look very different and aren't at all symmetric. If this is at all reasonable code, I found a couple of things non-obvious:

* The protected header could use an example in the docs. Otherwise you have to read large parts of the RFC to understand what it means.
* The protected argument to JWE is a string, I'd expected it to be a Python dict and assumed the API would take care of the conversion internally.
* It would be nice if there would be a key argument to ``JWE.__init__`` adding a default recipient. Since I use compact encoding, there can only be a single recipient and this would avoid the extra call to add_recipient.
* The JWE.deserialize function notes that it destroys the entire JWE state. Wouldn't it make more sense to change this into a class or staticmethod which internally creates a new JWE instance?
* JWE.deserialize has no return value. I expected it to return the plaintext and not get it from the payload property.

This is all well meant feedback after I used the library for a single purpose, so I might very well be missing larger implications or context.

Thanks! Hanno

**Comment by simo5** [comment]
Hi Hanno,
thanks a lot for your feedback.
* The docs indeed have examples only for JWK and JWT, I'll add Examples for JWS and JWE.
* The protected header is a JSON Encoded array, the reason why it is not a dict is that if you want identical outcomes out of 2 invocations you need to pass in a string that cannot change arbitrarily, dict's order is not guaranteed. However I can see how it may halpe to allow a dict, I will add code to accept a dict() if the user passes one in.
* I can add a recipient I guess, stay tuned
* I will think about the a deserialize static method, but not promises
* You can call deserialize w/o keys just to see if the general structure is a valid JWE, in that case there would be no plaintext to return, that's why the operation returns no data, it would have inconsistent behavior.

**Comment by hannosch** [comment]
Thanks for the real quick feedback and changes!

> I will think about the a deserialize static method, but not promises
> You can call deserialize w/o keys just to see if the general structure is a valid JWE, in that case there would be no plaintext to return, that's why the operation returns no data, it would have inconsistent behavior.

Ok, I didn't know about deserializing without keys. I guess one way to make this consistent would be to make deserialize a classmethod and return a new JWE instance. That way there would always be a return value. But I'm not too concerned with this. The warning message in the method ``Destroys any current status`` just struck me as odd. If it destroys any current state, why not just create a new instance instead and make that clear by the way you call the method, rather than having to read the docstring.

**Comment by simo5** [comment]
If I were starting from scratch I might go that way, but I do not wish to break APIs and ABIs now, so we'll have to live with what we have.
